# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c4b90c4995696721b75389bb8ce1d282bf0635f2d333de5ded026d4040f89310aaffdce07ba77b53d56542d03c4b5b89a7a9118a1ea8e2779be7bbb524597b8

test:
  secret_key_base: 292c9f823df716b5d8cc14fa53eeaec612576d53f3ba9918e34f2febbbea59bc638a62188383fb167b0bb2af8faacc9b1f4878e000e5e143c97b509784a33fed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
